// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: auth.proto

package protov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Login      string                 `protobuf:"bytes,1,opt,name=login,proto3"`
	xxx_hidden_Password   string                 `protobuf:"bytes,2,opt,name=password,proto3"`
	xxx_hidden_KekSalt    []byte                 `protobuf:"bytes,3,opt,name=kek_salt,json=kekSalt,proto3"`
	xxx_hidden_WrappedDek []byte                 `protobuf:"bytes,4,opt,name=wrapped_dek,json=wrappedDek,proto3"`
	xxx_hidden_KekParams  string                 `protobuf:"bytes,5,opt,name=kek_params,json=kekParams,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterRequest) GetLogin() string {
	if x != nil {
		return x.xxx_hidden_Login
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.xxx_hidden_Password
	}
	return ""
}

func (x *RegisterRequest) GetKekSalt() []byte {
	if x != nil {
		return x.xxx_hidden_KekSalt
	}
	return nil
}

func (x *RegisterRequest) GetWrappedDek() []byte {
	if x != nil {
		return x.xxx_hidden_WrappedDek
	}
	return nil
}

func (x *RegisterRequest) GetKekParams() string {
	if x != nil {
		return x.xxx_hidden_KekParams
	}
	return ""
}

func (x *RegisterRequest) SetLogin(v string) {
	x.xxx_hidden_Login = v
}

func (x *RegisterRequest) SetPassword(v string) {
	x.xxx_hidden_Password = v
}

func (x *RegisterRequest) SetKekSalt(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_KekSalt = v
}

func (x *RegisterRequest) SetWrappedDek(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_WrappedDek = v
}

func (x *RegisterRequest) SetKekParams(v string) {
	x.xxx_hidden_KekParams = v
}

type RegisterRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Login      string
	Password   string
	KekSalt    []byte
	WrappedDek []byte
	KekParams  string
}

func (b0 RegisterRequest_builder) Build() *RegisterRequest {
	m0 := &RegisterRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Login = b.Login
	x.xxx_hidden_Password = b.Password
	x.xxx_hidden_KekSalt = b.KekSalt
	x.xxx_hidden_WrappedDek = b.WrappedDek
	x.xxx_hidden_KekParams = b.KekParams
	return m0
}

type LoginRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Login    string                 `protobuf:"bytes,1,opt,name=login,proto3"`
	xxx_hidden_Password string                 `protobuf:"bytes,2,opt,name=password,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginRequest) GetLogin() string {
	if x != nil {
		return x.xxx_hidden_Login
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.xxx_hidden_Password
	}
	return ""
}

func (x *LoginRequest) SetLogin(v string) {
	x.xxx_hidden_Login = v
}

func (x *LoginRequest) SetPassword(v string) {
	x.xxx_hidden_Password = v
}

type LoginRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Login    string
	Password string
}

func (b0 LoginRequest_builder) Build() *LoginRequest {
	m0 := &LoginRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Login = b.Login
	x.xxx_hidden_Password = b.Password
	return m0
}

type RefreshTokenRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RefreshToken string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.xxx_hidden_RefreshToken
	}
	return ""
}

func (x *RefreshTokenRequest) SetRefreshToken(v string) {
	x.xxx_hidden_RefreshToken = v
}

type RefreshTokenRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RefreshToken string
}

func (b0 RefreshTokenRequest_builder) Build() *RefreshTokenRequest {
	m0 := &RefreshTokenRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RefreshToken = b.RefreshToken
	return m0
}

type LogoutRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RefreshToken string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LogoutRequest) GetRefreshToken() string {
	if x != nil {
		return x.xxx_hidden_RefreshToken
	}
	return ""
}

func (x *LogoutRequest) SetRefreshToken(v string) {
	x.xxx_hidden_RefreshToken = v
}

type LogoutRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RefreshToken string
}

func (b0 LogoutRequest_builder) Build() *LogoutRequest {
	m0 := &LogoutRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RefreshToken = b.RefreshToken
	return m0
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type LogoutResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 LogoutResponse_builder) Build() *LogoutResponse {
	m0 := &LogoutResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type AuthResponse struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_UserId       string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3"`
	xxx_hidden_AccessToken  string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3"`
	xxx_hidden_RefreshToken string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3"`
	xxx_hidden_ExpiresIn    int64                  `protobuf:"varint,4,opt,name=expires_in,json=expiresIn,proto3"`
	xxx_hidden_KekSalt      []byte                 `protobuf:"bytes,5,opt,name=kek_salt,json=kekSalt,proto3"`
	xxx_hidden_WrappedDek   []byte                 `protobuf:"bytes,6,opt,name=wrapped_dek,json=wrappedDek,proto3"`
	xxx_hidden_KekParams    string                 `protobuf:"bytes,7,opt,name=kek_params,json=kekParams,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthResponse) GetUserId() string {
	if x != nil {
		return x.xxx_hidden_UserId
	}
	return ""
}

func (x *AuthResponse) GetAccessToken() string {
	if x != nil {
		return x.xxx_hidden_AccessToken
	}
	return ""
}

func (x *AuthResponse) GetRefreshToken() string {
	if x != nil {
		return x.xxx_hidden_RefreshToken
	}
	return ""
}

func (x *AuthResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.xxx_hidden_ExpiresIn
	}
	return 0
}

func (x *AuthResponse) GetKekSalt() []byte {
	if x != nil {
		return x.xxx_hidden_KekSalt
	}
	return nil
}

func (x *AuthResponse) GetWrappedDek() []byte {
	if x != nil {
		return x.xxx_hidden_WrappedDek
	}
	return nil
}

func (x *AuthResponse) GetKekParams() string {
	if x != nil {
		return x.xxx_hidden_KekParams
	}
	return ""
}

func (x *AuthResponse) SetUserId(v string) {
	x.xxx_hidden_UserId = v
}

func (x *AuthResponse) SetAccessToken(v string) {
	x.xxx_hidden_AccessToken = v
}

func (x *AuthResponse) SetRefreshToken(v string) {
	x.xxx_hidden_RefreshToken = v
}

func (x *AuthResponse) SetExpiresIn(v int64) {
	x.xxx_hidden_ExpiresIn = v
}

func (x *AuthResponse) SetKekSalt(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_KekSalt = v
}

func (x *AuthResponse) SetWrappedDek(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_WrappedDek = v
}

func (x *AuthResponse) SetKekParams(v string) {
	x.xxx_hidden_KekParams = v
}

type AuthResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	UserId       string
	AccessToken  string
	RefreshToken string
	ExpiresIn    int64
	KekSalt      []byte
	WrappedDek   []byte
	KekParams    string
}

func (b0 AuthResponse_builder) Build() *AuthResponse {
	m0 := &AuthResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_UserId = b.UserId
	x.xxx_hidden_AccessToken = b.AccessToken
	x.xxx_hidden_RefreshToken = b.RefreshToken
	x.xxx_hidden_ExpiresIn = b.ExpiresIn
	x.xxx_hidden_KekSalt = b.KekSalt
	x.xxx_hidden_WrappedDek = b.WrappedDek
	x.xxx_hidden_KekParams = b.KekParams
	return m0
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\rgophkeeper.v1\"\x9e\x01\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x19\n" +
	"\bkek_salt\x18\x03 \x01(\fR\akekSalt\x12\x1f\n" +
	"\vwrapped_dek\x18\x04 \x01(\fR\n" +
	"wrappedDek\x12\x1d\n" +
	"\n" +
	"kek_params\x18\x05 \x01(\tR\tkekParams\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"4\n" +
	"\rLogoutRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\x10\n" +
	"\x0eLogoutResponse\"\xe9\x01\n" +
	"\fAuthResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x04 \x01(\x03R\texpiresIn\x12\x19\n" +
	"\bkek_salt\x18\x05 \x01(\fR\akekSalt\x12\x1f\n" +
	"\vwrapped_dek\x18\x06 \x01(\fR\n" +
	"wrappedDek\x12\x1d\n" +
	"\n" +
	"kek_params\x18\a \x01(\tR\tkekParams2\xb1\x02\n" +
	"\vAuthService\x12G\n" +
	"\bRegister\x12\x1e.gophkeeper.v1.RegisterRequest\x1a\x1b.gophkeeper.v1.AuthResponse\x12A\n" +
	"\x05Login\x12\x1b.gophkeeper.v1.LoginRequest\x1a\x1b.gophkeeper.v1.AuthResponse\x12O\n" +
	"\fRefreshToken\x12\".gophkeeper.v1.RefreshTokenRequest\x1a\x1b.gophkeeper.v1.AuthResponse\x12E\n" +
	"\x06Logout\x12\x1c.gophkeeper.v1.LogoutRequest\x1a\x1d.gophkeeper.v1.LogoutResponseB>Z<github.com/puzakov/gophkeeper-exam/internal/proto/v1;protov1b\x06proto3"

var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_auth_proto_goTypes = []any{
	(*RegisterRequest)(nil),     // 0: gophkeeper.v1.RegisterRequest
	(*LoginRequest)(nil),        // 1: gophkeeper.v1.LoginRequest
	(*RefreshTokenRequest)(nil), // 2: gophkeeper.v1.RefreshTokenRequest
	(*LogoutRequest)(nil),       // 3: gophkeeper.v1.LogoutRequest
	(*LogoutResponse)(nil),      // 4: gophkeeper.v1.LogoutResponse
	(*AuthResponse)(nil),        // 5: gophkeeper.v1.AuthResponse
}
var file_auth_proto_depIdxs = []int32{
	0, // 0: gophkeeper.v1.AuthService.Register:input_type -> gophkeeper.v1.RegisterRequest
	1, // 1: gophkeeper.v1.AuthService.Login:input_type -> gophkeeper.v1.LoginRequest
	2, // 2: gophkeeper.v1.AuthService.RefreshToken:input_type -> gophkeeper.v1.RefreshTokenRequest
	3, // 3: gophkeeper.v1.AuthService.Logout:input_type -> gophkeeper.v1.LogoutRequest
	5, // 4: gophkeeper.v1.AuthService.Register:output_type -> gophkeeper.v1.AuthResponse
	5, // 5: gophkeeper.v1.AuthService.Login:output_type -> gophkeeper.v1.AuthResponse
	5, // 6: gophkeeper.v1.AuthService.RefreshToken:output_type -> gophkeeper.v1.AuthResponse
	4, // 7: gophkeeper.v1.AuthService.Logout:output_type -> gophkeeper.v1.LogoutResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
