// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: secret.proto

package protov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SecretType enumerates the kinds of secrets the system can store.
type SecretType int32

const (
	SecretType_SECRET_TYPE_UNSPECIFIED    SecretType = 0
	SecretType_SECRET_TYPE_LOGIN_PASSWORD SecretType = 1
	SecretType_SECRET_TYPE_TEXT           SecretType = 2
	SecretType_SECRET_TYPE_BINARY         SecretType = 3
	SecretType_SECRET_TYPE_BANK_CARD      SecretType = 4
)

// Enum value maps for SecretType.
var (
	SecretType_name = map[int32]string{
		0: "SECRET_TYPE_UNSPECIFIED",
		1: "SECRET_TYPE_LOGIN_PASSWORD",
		2: "SECRET_TYPE_TEXT",
		3: "SECRET_TYPE_BINARY",
		4: "SECRET_TYPE_BANK_CARD",
	}
	SecretType_value = map[string]int32{
		"SECRET_TYPE_UNSPECIFIED":    0,
		"SECRET_TYPE_LOGIN_PASSWORD": 1,
		"SECRET_TYPE_TEXT":           2,
		"SECRET_TYPE_BINARY":         3,
		"SECRET_TYPE_BANK_CARD":      4,
	}
)

func (x SecretType) Enum() *SecretType {
	p := new(SecretType)
	*p = x
	return p
}

func (x SecretType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecretType) Descriptor() protoreflect.EnumDescriptor {
	return file_secret_proto_enumTypes[0].Descriptor()
}

func (SecretType) Type() protoreflect.EnumType {
	return &file_secret_proto_enumTypes[0]
}

func (x SecretType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecretType.Descriptor instead.
func (SecretType) EnumDescriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{0}
}

// Secret is the full representation including encrypted payloads.
type Secret struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type              SecretType             `protobuf:"varint,2,opt,name=type,proto3,enum=gophkeeper.v1.SecretType" json:"type,omitempty"`
	EncryptedData     []byte                 `protobuf:"bytes,3,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"`             // AES-256-GCM: nonce || ciphertext || tag
	EncryptedMetadata []byte                 `protobuf:"bytes,4,opt,name=encrypted_metadata,json=encryptedMetadata,proto3" json:"encrypted_metadata,omitempty"` // same envelope; arbitrary key/value pairs
	Comment           string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`                                              // plaintext label for listing (non-sensitive)
	Version           int64                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt         int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix seconds
	UpdatedAt         int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // unix seconds
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_secret_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{0}
}

func (x *Secret) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Secret) GetType() SecretType {
	if x != nil {
		return x.Type
	}
	return SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *Secret) GetEncryptedData() []byte {
	if x != nil {
		return x.EncryptedData
	}
	return nil
}

func (x *Secret) GetEncryptedMetadata() []byte {
	if x != nil {
		return x.EncryptedMetadata
	}
	return nil
}

func (x *Secret) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Secret) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Secret) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Secret) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// SecretSummary contains metadata only — used by ListSecrets to avoid
// downloading encrypted blobs for every item.
type SecretSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          SecretType             `protobuf:"varint,2,opt,name=type,proto3,enum=gophkeeper.v1.SecretType" json:"type,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretSummary) Reset() {
	*x = SecretSummary{}
	mi := &file_secret_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretSummary) ProtoMessage() {}

func (x *SecretSummary) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretSummary.ProtoReflect.Descriptor instead.
func (*SecretSummary) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{1}
}

func (x *SecretSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SecretSummary) GetType() SecretType {
	if x != nil {
		return x.Type
	}
	return SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *SecretSummary) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *SecretSummary) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SecretSummary) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreateSecretRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Type              SecretType             `protobuf:"varint,1,opt,name=type,proto3,enum=gophkeeper.v1.SecretType" json:"type,omitempty"`
	EncryptedData     []byte                 `protobuf:"bytes,2,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"`
	EncryptedMetadata []byte                 `protobuf:"bytes,3,opt,name=encrypted_metadata,json=encryptedMetadata,proto3" json:"encrypted_metadata,omitempty"`
	Comment           string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateSecretRequest) Reset() {
	*x = CreateSecretRequest{}
	mi := &file_secret_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretRequest) ProtoMessage() {}

func (x *CreateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretRequest.ProtoReflect.Descriptor instead.
func (*CreateSecretRequest) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSecretRequest) GetType() SecretType {
	if x != nil {
		return x.Type
	}
	return SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *CreateSecretRequest) GetEncryptedData() []byte {
	if x != nil {
		return x.EncryptedData
	}
	return nil
}

func (x *CreateSecretRequest) GetEncryptedMetadata() []byte {
	if x != nil {
		return x.EncryptedMetadata
	}
	return nil
}

func (x *CreateSecretRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type CreateSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretResponse) Reset() {
	*x = CreateSecretResponse{}
	mi := &file_secret_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretResponse) ProtoMessage() {}

func (x *CreateSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretResponse.ProtoReflect.Descriptor instead.
func (*CreateSecretResponse) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSecretResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateSecretResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretRequest) Reset() {
	*x = GetSecretRequest{}
	mi := &file_secret_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretRequest) ProtoMessage() {}

func (x *GetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretRequest.ProtoReflect.Descriptor instead.
func (*GetSecretRequest) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{4}
}

func (x *GetSecretRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        *Secret                `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretResponse) Reset() {
	*x = GetSecretResponse{}
	mi := &file_secret_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretResponse) ProtoMessage() {}

func (x *GetSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretResponse.ProtoReflect.Descriptor instead.
func (*GetSecretResponse) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{5}
}

func (x *GetSecretResponse) GetSecret() *Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

type ListSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsRequest) Reset() {
	*x = ListSecretsRequest{}
	mi := &file_secret_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsRequest) ProtoMessage() {}

func (x *ListSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsRequest.ProtoReflect.Descriptor instead.
func (*ListSecretsRequest) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{6}
}

type ListSecretsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secrets       []*SecretSummary       `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsResponse) Reset() {
	*x = ListSecretsResponse{}
	mi := &file_secret_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsResponse) ProtoMessage() {}

func (x *ListSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsResponse.ProtoReflect.Descriptor instead.
func (*ListSecretsResponse) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{7}
}

func (x *ListSecretsResponse) GetSecrets() []*SecretSummary {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type UpdateSecretRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExpectedVersion   int64                  `protobuf:"varint,2,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"` // optimistic concurrency
	EncryptedData     []byte                 `protobuf:"bytes,3,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"`
	EncryptedMetadata []byte                 `protobuf:"bytes,4,opt,name=encrypted_metadata,json=encryptedMetadata,proto3" json:"encrypted_metadata,omitempty"`
	Comment           string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateSecretRequest) Reset() {
	*x = UpdateSecretRequest{}
	mi := &file_secret_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretRequest) ProtoMessage() {}

func (x *UpdateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecretRequest.ProtoReflect.Descriptor instead.
func (*UpdateSecretRequest) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateSecretRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSecretRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

func (x *UpdateSecretRequest) GetEncryptedData() []byte {
	if x != nil {
		return x.EncryptedData
	}
	return nil
}

func (x *UpdateSecretRequest) GetEncryptedMetadata() []byte {
	if x != nil {
		return x.EncryptedMetadata
	}
	return nil
}

func (x *UpdateSecretRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type UpdateSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSecretResponse) Reset() {
	*x = UpdateSecretResponse{}
	mi := &file_secret_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretResponse) ProtoMessage() {}

func (x *UpdateSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecretResponse.ProtoReflect.Descriptor instead.
func (*UpdateSecretResponse) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateSecretResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type DeleteSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretRequest) Reset() {
	*x = DeleteSecretRequest{}
	mi := &file_secret_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretRequest) ProtoMessage() {}

func (x *DeleteSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretRequest.ProtoReflect.Descriptor instead.
func (*DeleteSecretRequest) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteSecretRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretResponse) Reset() {
	*x = DeleteSecretResponse{}
	mi := &file_secret_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretResponse) ProtoMessage() {}

func (x *DeleteSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretResponse.ProtoReflect.Descriptor instead.
func (*DeleteSecretResponse) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{11}
}

var File_secret_proto protoreflect.FileDescriptor

const file_secret_proto_rawDesc = "" +
	"\n" +
	"\fsecret.proto\x12\rgophkeeper.v1\"\x8f\x02\n" +
	"\x06Secret\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.gophkeeper.v1.SecretTypeR\x04type\x12%\n" +
	"\x0eencrypted_data\x18\x03 \x01(\fR\rencryptedData\x12-\n" +
	"\x12encrypted_metadata\x18\x04 \x01(\fR\x11encryptedMetadata\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\"\xa1\x01\n" +
	"\rSecretSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.gophkeeper.v1.SecretTypeR\x04type\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\"\xb4\x01\n" +
	"\x13CreateSecretRequest\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.gophkeeper.v1.SecretTypeR\x04type\x12%\n" +
	"\x0eencrypted_data\x18\x02 \x01(\fR\rencryptedData\x12-\n" +
	"\x12encrypted_metadata\x18\x03 \x01(\fR\x11encryptedMetadata\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\"@\n" +
	"\x14CreateSecretResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\"\"\n" +
	"\x10GetSecretRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"B\n" +
	"\x11GetSecretResponse\x12-\n" +
	"\x06secret\x18\x01 \x01(\v2\x15.gophkeeper.v1.SecretR\x06secret\"\x14\n" +
	"\x12ListSecretsRequest\"M\n" +
	"\x13ListSecretsResponse\x126\n" +
	"\asecrets\x18\x01 \x03(\v2\x1c.gophkeeper.v1.SecretSummaryR\asecrets\"\xc0\x01\n" +
	"\x13UpdateSecretRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x10expected_version\x18\x02 \x01(\x03R\x0fexpectedVersion\x12%\n" +
	"\x0eencrypted_data\x18\x03 \x01(\fR\rencryptedData\x12-\n" +
	"\x12encrypted_metadata\x18\x04 \x01(\fR\x11encryptedMetadata\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\"0\n" +
	"\x14UpdateSecretResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\"%\n" +
	"\x13DeleteSecretRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x14DeleteSecretResponse*\x92\x01\n" +
	"\n" +
	"SecretType\x12\x1b\n" +
	"\x17SECRET_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSECRET_TYPE_LOGIN_PASSWORD\x10\x01\x12\x14\n" +
	"\x10SECRET_TYPE_TEXT\x10\x02\x12\x16\n" +
	"\x12SECRET_TYPE_BINARY\x10\x03\x12\x19\n" +
	"\x15SECRET_TYPE_BANK_CARD\x10\x042\xc0\x03\n" +
	"\rSecretService\x12W\n" +
	"\fCreateSecret\x12\".gophkeeper.v1.CreateSecretRequest\x1a#.gophkeeper.v1.CreateSecretResponse\x12N\n" +
	"\tGetSecret\x12\x1f.gophkeeper.v1.GetSecretRequest\x1a .gophkeeper.v1.GetSecretResponse\x12T\n" +
	"\vListSecrets\x12!.gophkeeper.v1.ListSecretsRequest\x1a\".gophkeeper.v1.ListSecretsResponse\x12W\n" +
	"\fUpdateSecret\x12\".gophkeeper.v1.UpdateSecretRequest\x1a#.gophkeeper.v1.UpdateSecretResponse\x12W\n" +
	"\fDeleteSecret\x12\".gophkeeper.v1.DeleteSecretRequest\x1a#.gophkeeper.v1.DeleteSecretResponseB>Z<github.com/puzakov/gophkeeper-exam/internal/proto/v1;protov1b\x06proto3"

var (
	file_secret_proto_rawDescOnce sync.Once
	file_secret_proto_rawDescData []byte
)

func file_secret_proto_rawDescGZIP() []byte {
	file_secret_proto_rawDescOnce.Do(func() {
		file_secret_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_secret_proto_rawDesc), len(file_secret_proto_rawDesc)))
	})
	return file_secret_proto_rawDescData
}

var file_secret_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_secret_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_secret_proto_goTypes = []any{
	(SecretType)(0),              // 0: gophkeeper.v1.SecretType
	(*Secret)(nil),               // 1: gophkeeper.v1.Secret
	(*SecretSummary)(nil),        // 2: gophkeeper.v1.SecretSummary
	(*CreateSecretRequest)(nil),  // 3: gophkeeper.v1.CreateSecretRequest
	(*CreateSecretResponse)(nil), // 4: gophkeeper.v1.CreateSecretResponse
	(*GetSecretRequest)(nil),     // 5: gophkeeper.v1.GetSecretRequest
	(*GetSecretResponse)(nil),    // 6: gophkeeper.v1.GetSecretResponse
	(*ListSecretsRequest)(nil),   // 7: gophkeeper.v1.ListSecretsRequest
	(*ListSecretsResponse)(nil),  // 8: gophkeeper.v1.ListSecretsResponse
	(*UpdateSecretRequest)(nil),  // 9: gophkeeper.v1.UpdateSecretRequest
	(*UpdateSecretResponse)(nil), // 10: gophkeeper.v1.UpdateSecretResponse
	(*DeleteSecretRequest)(nil),  // 11: gophkeeper.v1.DeleteSecretRequest
	(*DeleteSecretResponse)(nil), // 12: gophkeeper.v1.DeleteSecretResponse
}
var file_secret_proto_depIdxs = []int32{
	0,  // 0: gophkeeper.v1.Secret.type:type_name -> gophkeeper.v1.SecretType
	0,  // 1: gophkeeper.v1.SecretSummary.type:type_name -> gophkeeper.v1.SecretType
	0,  // 2: gophkeeper.v1.CreateSecretRequest.type:type_name -> gophkeeper.v1.SecretType
	1,  // 3: gophkeeper.v1.GetSecretResponse.secret:type_name -> gophkeeper.v1.Secret
	2,  // 4: gophkeeper.v1.ListSecretsResponse.secrets:type_name -> gophkeeper.v1.SecretSummary
	3,  // 5: gophkeeper.v1.SecretService.CreateSecret:input_type -> gophkeeper.v1.CreateSecretRequest
	5,  // 6: gophkeeper.v1.SecretService.GetSecret:input_type -> gophkeeper.v1.GetSecretRequest
	7,  // 7: gophkeeper.v1.SecretService.ListSecrets:input_type -> gophkeeper.v1.ListSecretsRequest
	9,  // 8: gophkeeper.v1.SecretService.UpdateSecret:input_type -> gophkeeper.v1.UpdateSecretRequest
	11, // 9: gophkeeper.v1.SecretService.DeleteSecret:input_type -> gophkeeper.v1.DeleteSecretRequest
	4,  // 10: gophkeeper.v1.SecretService.CreateSecret:output_type -> gophkeeper.v1.CreateSecretResponse
	6,  // 11: gophkeeper.v1.SecretService.GetSecret:output_type -> gophkeeper.v1.GetSecretResponse
	8,  // 12: gophkeeper.v1.SecretService.ListSecrets:output_type -> gophkeeper.v1.ListSecretsResponse
	10, // 13: gophkeeper.v1.SecretService.UpdateSecret:output_type -> gophkeeper.v1.UpdateSecretResponse
	12, // 14: gophkeeper.v1.SecretService.DeleteSecret:output_type -> gophkeeper.v1.DeleteSecretResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_secret_proto_init() }
func file_secret_proto_init() {
	if File_secret_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_secret_proto_rawDesc), len(file_secret_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_secret_proto_goTypes,
		DependencyIndexes: file_secret_proto_depIdxs,
		EnumInfos:         file_secret_proto_enumTypes,
		MessageInfos:      file_secret_proto_msgTypes,
	}.Build()
	File_secret_proto = out.File
	file_secret_proto_goTypes = nil
	file_secret_proto_depIdxs = nil
}
