// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: sync.proto

package protov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SyncVersion holds a client's knowledge about a secret's latest version.
type SyncVersion struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SecretId string                 `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3"`
	xxx_hidden_Version  int64                  `protobuf:"varint,2,opt,name=version,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SyncVersion) Reset() {
	*x = SyncVersion{}
	mi := &file_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncVersion) ProtoMessage() {}

func (x *SyncVersion) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SyncVersion) GetSecretId() string {
	if x != nil {
		return x.xxx_hidden_SecretId
	}
	return ""
}

func (x *SyncVersion) GetVersion() int64 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *SyncVersion) SetSecretId(v string) {
	x.xxx_hidden_SecretId = v
}

func (x *SyncVersion) SetVersion(v int64) {
	x.xxx_hidden_Version = v
}

type SyncVersion_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SecretId string
	Version  int64
}

func (b0 SyncVersion_builder) Build() *SyncVersion {
	m0 := &SyncVersion{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SecretId = b.SecretId
	x.xxx_hidden_Version = b.Version
	return m0
}

type SyncSecretsRequest struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ClientVersions *[]*SyncVersion        `protobuf:"bytes,1,rep,name=client_versions,json=clientVersions,proto3"`
	xxx_hidden_ClientDeleted  []string               `protobuf:"bytes,2,rep,name=client_deleted,json=clientDeleted,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *SyncSecretsRequest) Reset() {
	*x = SyncSecretsRequest{}
	mi := &file_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSecretsRequest) ProtoMessage() {}

func (x *SyncSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SyncSecretsRequest) GetClientVersions() []*SyncVersion {
	if x != nil {
		if x.xxx_hidden_ClientVersions != nil {
			return *x.xxx_hidden_ClientVersions
		}
	}
	return nil
}

func (x *SyncSecretsRequest) GetClientDeleted() []string {
	if x != nil {
		return x.xxx_hidden_ClientDeleted
	}
	return nil
}

func (x *SyncSecretsRequest) SetClientVersions(v []*SyncVersion) {
	x.xxx_hidden_ClientVersions = &v
}

func (x *SyncSecretsRequest) SetClientDeleted(v []string) {
	x.xxx_hidden_ClientDeleted = v
}

type SyncSecretsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ClientVersions []*SyncVersion
	ClientDeleted  []string
}

func (b0 SyncSecretsRequest_builder) Build() *SyncSecretsRequest {
	m0 := &SyncSecretsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ClientVersions = &b.ClientVersions
	x.xxx_hidden_ClientDeleted = b.ClientDeleted
	return m0
}

type SyncSecretsResponse struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_UpdatedSecrets *[]*Secret             `protobuf:"bytes,1,rep,name=updated_secrets,json=updatedSecrets,proto3"`
	xxx_hidden_DeletedIds     []string               `protobuf:"bytes,2,rep,name=deleted_ids,json=deletedIds,proto3"`
	xxx_hidden_Conflicts      *[]*SyncVersion        `protobuf:"bytes,3,rep,name=conflicts,proto3"`
	xxx_hidden_ServerVersions *[]*SyncVersion        `protobuf:"bytes,4,rep,name=server_versions,json=serverVersions,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *SyncSecretsResponse) Reset() {
	*x = SyncSecretsResponse{}
	mi := &file_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSecretsResponse) ProtoMessage() {}

func (x *SyncSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SyncSecretsResponse) GetUpdatedSecrets() []*Secret {
	if x != nil {
		if x.xxx_hidden_UpdatedSecrets != nil {
			return *x.xxx_hidden_UpdatedSecrets
		}
	}
	return nil
}

func (x *SyncSecretsResponse) GetDeletedIds() []string {
	if x != nil {
		return x.xxx_hidden_DeletedIds
	}
	return nil
}

func (x *SyncSecretsResponse) GetConflicts() []*SyncVersion {
	if x != nil {
		if x.xxx_hidden_Conflicts != nil {
			return *x.xxx_hidden_Conflicts
		}
	}
	return nil
}

func (x *SyncSecretsResponse) GetServerVersions() []*SyncVersion {
	if x != nil {
		if x.xxx_hidden_ServerVersions != nil {
			return *x.xxx_hidden_ServerVersions
		}
	}
	return nil
}

func (x *SyncSecretsResponse) SetUpdatedSecrets(v []*Secret) {
	x.xxx_hidden_UpdatedSecrets = &v
}

func (x *SyncSecretsResponse) SetDeletedIds(v []string) {
	x.xxx_hidden_DeletedIds = v
}

func (x *SyncSecretsResponse) SetConflicts(v []*SyncVersion) {
	x.xxx_hidden_Conflicts = &v
}

func (x *SyncSecretsResponse) SetServerVersions(v []*SyncVersion) {
	x.xxx_hidden_ServerVersions = &v
}

type SyncSecretsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	UpdatedSecrets []*Secret
	DeletedIds     []string
	Conflicts      []*SyncVersion
	ServerVersions []*SyncVersion
}

func (b0 SyncSecretsResponse_builder) Build() *SyncSecretsResponse {
	m0 := &SyncSecretsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_UpdatedSecrets = &b.UpdatedSecrets
	x.xxx_hidden_DeletedIds = b.DeletedIds
	x.xxx_hidden_Conflicts = &b.Conflicts
	x.xxx_hidden_ServerVersions = &b.ServerVersions
	return m0
}

var File_sync_proto protoreflect.FileDescriptor

const file_sync_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"sync.proto\x12\rgophkeeper.v1\x1a\fsecret.proto\"D\n" +
	"\vSyncVersion\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\"\x80\x01\n" +
	"\x12SyncSecretsRequest\x12C\n" +
	"\x0fclient_versions\x18\x01 \x03(\v2\x1a.gophkeeper.v1.SyncVersionR\x0eclientVersions\x12%\n" +
	"\x0eclient_deleted\x18\x02 \x03(\tR\rclientDeleted\"\xf5\x01\n" +
	"\x13SyncSecretsResponse\x12>\n" +
	"\x0fupdated_secrets\x18\x01 \x03(\v2\x15.gophkeeper.v1.SecretR\x0eupdatedSecrets\x12\x1f\n" +
	"\vdeleted_ids\x18\x02 \x03(\tR\n" +
	"deletedIds\x128\n" +
	"\tconflicts\x18\x03 \x03(\v2\x1a.gophkeeper.v1.SyncVersionR\tconflicts\x12C\n" +
	"\x0fserver_versions\x18\x04 \x03(\v2\x1a.gophkeeper.v1.SyncVersionR\x0eserverVersions2c\n" +
	"\vSyncService\x12T\n" +
	"\vSyncSecrets\x12!.gophkeeper.v1.SyncSecretsRequest\x1a\".gophkeeper.v1.SyncSecretsResponseB>Z<github.com/puzakov/gophkeeper-exam/internal/proto/v1;protov1b\x06proto3"

var file_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sync_proto_goTypes = []any{
	(*SyncVersion)(nil),         // 0: gophkeeper.v1.SyncVersion
	(*SyncSecretsRequest)(nil),  // 1: gophkeeper.v1.SyncSecretsRequest
	(*SyncSecretsResponse)(nil), // 2: gophkeeper.v1.SyncSecretsResponse
	(*Secret)(nil),              // 3: gophkeeper.v1.Secret
}
var file_sync_proto_depIdxs = []int32{
	0, // 0: gophkeeper.v1.SyncSecretsRequest.client_versions:type_name -> gophkeeper.v1.SyncVersion
	3, // 1: gophkeeper.v1.SyncSecretsResponse.updated_secrets:type_name -> gophkeeper.v1.Secret
	0, // 2: gophkeeper.v1.SyncSecretsResponse.conflicts:type_name -> gophkeeper.v1.SyncVersion
	0, // 3: gophkeeper.v1.SyncSecretsResponse.server_versions:type_name -> gophkeeper.v1.SyncVersion
	1, // 4: gophkeeper.v1.SyncService.SyncSecrets:input_type -> gophkeeper.v1.SyncSecretsRequest
	2, // 5: gophkeeper.v1.SyncService.SyncSecrets:output_type -> gophkeeper.v1.SyncSecretsResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sync_proto_init() }
func file_sync_proto_init() {
	if File_sync_proto != nil {
		return
	}
	file_secret_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sync_proto_rawDesc), len(file_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sync_proto_goTypes,
		DependencyIndexes: file_sync_proto_depIdxs,
		MessageInfos:      file_sync_proto_msgTypes,
	}.Build()
	File_sync_proto = out.File
	file_sync_proto_goTypes = nil
	file_sync_proto_depIdxs = nil
}
