// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: sync.proto

package protov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SyncVersion holds a client's knowledge about a secret's latest version.
type SyncVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretId      string                 `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncVersion) Reset() {
	*x = SyncVersion{}
	mi := &file_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncVersion) ProtoMessage() {}

func (x *SyncVersion) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncVersion.ProtoReflect.Descriptor instead.
func (*SyncVersion) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{0}
}

func (x *SyncVersion) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *SyncVersion) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type SyncSecretsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientVersions []*SyncVersion         `protobuf:"bytes,1,rep,name=client_versions,json=clientVersions,proto3" json:"client_versions,omitempty"` // secrets the client already has
	ClientDeleted  []string               `protobuf:"bytes,2,rep,name=client_deleted,json=clientDeleted,proto3" json:"client_deleted,omitempty"`    // ids client deleted locally, not yet acked
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncSecretsRequest) Reset() {
	*x = SyncSecretsRequest{}
	mi := &file_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSecretsRequest) ProtoMessage() {}

func (x *SyncSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncSecretsRequest.ProtoReflect.Descriptor instead.
func (*SyncSecretsRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{1}
}

func (x *SyncSecretsRequest) GetClientVersions() []*SyncVersion {
	if x != nil {
		return x.ClientVersions
	}
	return nil
}

func (x *SyncSecretsRequest) GetClientDeleted() []string {
	if x != nil {
		return x.ClientDeleted
	}
	return nil
}

type SyncSecretsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UpdatedSecrets []*Secret              `protobuf:"bytes,1,rep,name=updated_secrets,json=updatedSecrets,proto3" json:"updated_secrets,omitempty"` // server version > client version
	DeletedIds     []string               `protobuf:"bytes,2,rep,name=deleted_ids,json=deletedIds,proto3" json:"deleted_ids,omitempty"`             // server tombstone newer than client version
	Conflicts      []*SyncVersion         `protobuf:"bytes,3,rep,name=conflicts,proto3" json:"conflicts,omitempty"`                                 // client version > server → re-push
	ServerVersions []*SyncVersion         `protobuf:"bytes,4,rep,name=server_versions,json=serverVersions,proto3" json:"server_versions,omitempty"` // full current version map for reconciliation
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncSecretsResponse) Reset() {
	*x = SyncSecretsResponse{}
	mi := &file_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSecretsResponse) ProtoMessage() {}

func (x *SyncSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncSecretsResponse.ProtoReflect.Descriptor instead.
func (*SyncSecretsResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{2}
}

func (x *SyncSecretsResponse) GetUpdatedSecrets() []*Secret {
	if x != nil {
		return x.UpdatedSecrets
	}
	return nil
}

func (x *SyncSecretsResponse) GetDeletedIds() []string {
	if x != nil {
		return x.DeletedIds
	}
	return nil
}

func (x *SyncSecretsResponse) GetConflicts() []*SyncVersion {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

func (x *SyncSecretsResponse) GetServerVersions() []*SyncVersion {
	if x != nil {
		return x.ServerVersions
	}
	return nil
}

var File_sync_proto protoreflect.FileDescriptor

const file_sync_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"sync.proto\x12\rgophkeeper.v1\x1a\fsecret.proto\"D\n" +
	"\vSyncVersion\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\"\x80\x01\n" +
	"\x12SyncSecretsRequest\x12C\n" +
	"\x0fclient_versions\x18\x01 \x03(\v2\x1a.gophkeeper.v1.SyncVersionR\x0eclientVersions\x12%\n" +
	"\x0eclient_deleted\x18\x02 \x03(\tR\rclientDeleted\"\xf5\x01\n" +
	"\x13SyncSecretsResponse\x12>\n" +
	"\x0fupdated_secrets\x18\x01 \x03(\v2\x15.gophkeeper.v1.SecretR\x0eupdatedSecrets\x12\x1f\n" +
	"\vdeleted_ids\x18\x02 \x03(\tR\n" +
	"deletedIds\x128\n" +
	"\tconflicts\x18\x03 \x03(\v2\x1a.gophkeeper.v1.SyncVersionR\tconflicts\x12C\n" +
	"\x0fserver_versions\x18\x04 \x03(\v2\x1a.gophkeeper.v1.SyncVersionR\x0eserverVersions2c\n" +
	"\vSyncService\x12T\n" +
	"\vSyncSecrets\x12!.gophkeeper.v1.SyncSecretsRequest\x1a\".gophkeeper.v1.SyncSecretsResponseB>Z<github.com/puzakov/gophkeeper-exam/internal/proto/v1;protov1b\x06proto3"

var (
	file_sync_proto_rawDescOnce sync.Once
	file_sync_proto_rawDescData []byte
)

func file_sync_proto_rawDescGZIP() []byte {
	file_sync_proto_rawDescOnce.Do(func() {
		file_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sync_proto_rawDesc), len(file_sync_proto_rawDesc)))
	})
	return file_sync_proto_rawDescData
}

var file_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sync_proto_goTypes = []any{
	(*SyncVersion)(nil),         // 0: gophkeeper.v1.SyncVersion
	(*SyncSecretsRequest)(nil),  // 1: gophkeeper.v1.SyncSecretsRequest
	(*SyncSecretsResponse)(nil), // 2: gophkeeper.v1.SyncSecretsResponse
	(*Secret)(nil),              // 3: gophkeeper.v1.Secret
}
var file_sync_proto_depIdxs = []int32{
	0, // 0: gophkeeper.v1.SyncSecretsRequest.client_versions:type_name -> gophkeeper.v1.SyncVersion
	3, // 1: gophkeeper.v1.SyncSecretsResponse.updated_secrets:type_name -> gophkeeper.v1.Secret
	0, // 2: gophkeeper.v1.SyncSecretsResponse.conflicts:type_name -> gophkeeper.v1.SyncVersion
	0, // 3: gophkeeper.v1.SyncSecretsResponse.server_versions:type_name -> gophkeeper.v1.SyncVersion
	1, // 4: gophkeeper.v1.SyncService.SyncSecrets:input_type -> gophkeeper.v1.SyncSecretsRequest
	2, // 5: gophkeeper.v1.SyncService.SyncSecrets:output_type -> gophkeeper.v1.SyncSecretsResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sync_proto_init() }
func file_sync_proto_init() {
	if File_sync_proto != nil {
		return
	}
	file_secret_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sync_proto_rawDesc), len(file_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sync_proto_goTypes,
		DependencyIndexes: file_sync_proto_depIdxs,
		MessageInfos:      file_sync_proto_msgTypes,
	}.Build()
	File_sync_proto = out.File
	file_sync_proto_goTypes = nil
	file_sync_proto_depIdxs = nil
}
